name: CI/CD - AWS Lambda Java

on:
  push:
    branches:
      - main
      - homologation
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'homologation' }}

jobs:
  deploy:
    name: Build and Deploy to ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'homologation' }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven (Gera o Fat JAR)
        working-directory: DocumentAuthFunction
        run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init -backend-config="key=lambda/${{ env.ENVIRONMENT }}/terraform.tfstate"

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}